In [65]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [66]:
#Detect lines in chess board
chessoriginal = cv2.imread("/home/ashritha/ImageProcessing/HoughTransform/chess.png")
chess = cv2.cvtColor(chessoriginal,cv2.COLOR_BGR2GRAY)

In [76]:
plt.imshow(chess,cmap="gray")
plt.show()
cv2.imwrite("/home/ashritha/ImageProcessing/HoughTransform/chessgray.png",chess)

True

In [68]:
edges = cv2.Canny(chess,100,200)

In [77]:
plt.imshow(edges,cmap="gray")
plt.show()
cv2.imwrite("/home/ashritha/ImageProcessing/HoughTransform/chessedges.png",edges)

True

In [46]:
help(cv2.HoughLines)

Help on built-in function HoughLines:

HoughLines(...)
    HoughLines(image, rho, theta, threshold[, lines[, srn[, stn[, min_theta[, max_theta]]]]]) -> lines



In [71]:
lines = cv2.HoughLines(edges,1,np.pi/180,100)

In [72]:
lines

array([[[  24.        ,    0.        ]],

       [[  49.        ,    0.        ]],

       [[  74.        ,    0.        ]],

       [[  99.        ,    0.        ]],

       [[ 124.        ,    0.        ]],

       [[ 149.        ,    0.        ]],

       [[ 174.        ,    0.        ]],

       [[  24.        ,    1.57079637]],

       [[  49.        ,    1.57079637]],

       [[  74.        ,    1.57079637]],

       [[  99.        ,    1.57079637]],

       [[ 124.        ,    1.57079637]],

       [[ 149.        ,    1.57079637]],

       [[ 174.        ,    1.57079637]]], dtype=float32)

In [73]:
lines.shape

(14, 1, 2)

In [74]:
for i in range(lines.shape[0]):
    for rho,theta in lines[i]:
        a = np.cos(theta)
        b = np.sin(theta)
        x0 = a*rho
        y0 = b*rho
        x1 = int(x0+1000*(-b))
        y1 = int(y0+1000*a)
        x2 = int(x0-1000*(-b))
        y2 = int(y0-1000*a)
        cv2.line(chessoriginal,(x1,y1),(x2,y2),(0,0,255),2)
    cv2.imwrite("/home/ashritha/ImageProcessing/HoughTransform/chess.png",chessoriginal)

In [75]:
plt.imshow(chessoriginal)
plt.show()

In [126]:
#Detect lines in an image
linesoriginal = cv2.imread("/home/ashritha/ImageProcessing/HoughTransform/lines.jpeg")

In [127]:
lines = cv2.cvtColor(linesoriginal,cv2.COLOR_BGR2GRAY)

In [128]:
plt.imshow(lines,cmap="gray")
plt.show()
cv2.imwrite("/home/ashritha/ImageProcessing/HoughTransform/linesgray.jpeg",lines)

True

In [129]:
edges = cv2.Canny(lines,100,200)

In [130]:
plt.imshow(edges,cmap="gray")
plt.show()

In [137]:
houghLines = cv2.HoughLines(edges,1,np.pi/180,130)

In [138]:
houghLines

array([[[ 156.        ,    0.78539819]],

       [[ 144.        ,    0.78539819]],

       [[ 168.        ,    0.78539819]],

       [[ 177.        ,    0.78539819]],

       [[ 132.        ,    0.78539819]],

       [[ 153.        ,    0.78539819]],

       [[ 165.        ,    0.78539819]],

       [[ 180.        ,    0.78539819]],

       [[ 120.        ,    0.78539819]],

       [[ 141.        ,    0.78539819]],

       [[ 192.        ,    0.78539819]],

       [[ 129.        ,    0.78539819]],

       [[ 151.        ,    0.78539819]],

       [[ 162.        ,    0.78539819]],

       [[ 139.        ,    0.78539819]],

       [[ 174.        ,    0.78539819]],

       [[ 182.        ,    0.78539819]],

       [[ 127.        ,    0.78539819]],

       [[ 170.        ,    0.78539819]],

       [[ 204.        ,    0.78539819]],

       [[ 190.        ,    0.78539819]],

       [[ 117.        ,    0.78539819]],

       [[ 186.        ,    0.78539819]],

       [[ 158.        ,    0.78539

In [139]:
houghLines.shape

(84, 1, 2)

In [140]:
for i in range(houghLines.shape[0]):
    for rho,theta in houghLines[i]:
        a = np.cos(theta)
        b = np.sin(theta)
        x0 = a*rho
        y0 = b*rho
        x1 = int(a+1000*(-b))
        y1 = int(b+1000*(a))
        x2 = int(a-1000*(-b))
        y2 = int(b-1000*(a))
        cv2.line(linesoriginal,(x1,y1),(x2,y2),(0,0,255),1)
    cv2.imwrite("/home/ashritha/ImageProcessing/HoughTransform/lines.jpeg",linesoriginal)

In [141]:
plt.imshow(linesoriginal)
plt.show()

In [185]:
#HoughTransform -Circles
logo = cv2.imread("/home/ashritha/ImageProcessing/HoughTransform/logo.png")

In [186]:
plt.imshow(logo)
plt.show()

In [187]:
logogray = cv2.cvtColor(logo,cv2.COLOR_BGR2GRAY)

In [188]:
plt.imshow(logogray,cmap="gray")
plt.show()
cv2.imwrite("/home/ashritha/ImageProcessing/HoughTransform/logogray.png",logogray)

True

In [189]:
help(cv2.HoughCircles)

Help on built-in function HoughCircles:

HoughCircles(...)
    HoughCircles(image, method, dp, minDist[, circles[, param1[, param2[, minRadius[, maxRadius]]]]]) -> circles



In [191]:
circles = cv2.HoughCircles(logogray,cv2.HOUGH_GRADIENT,1,20,param1=50,param2=30,minRadius = 0, maxRadius = 0)

In [192]:
circles

array([[[ 449.5       ,  416.5       ,  133.26850891],
        [ 152.5       ,  419.5       ,  151.56680298],
        [ 251.5       ,  662.5       ,   26.54241753],
        [ 130.5       ,  411.5       ,   66.10975647],
        [  58.5       ,  650.5       ,   54.88624573],
        [ 160.5       ,  672.5       ,   17.67766953],
        [ 302.5       ,  143.5       ,  145.802948  ],
        [ 438.5       ,  656.5       ,   51.21035004],
        [  56.5       ,  625.5       ,   50.81830215],
        [ 437.5       ,  634.5       ,   50.81830215],
        [ 468.5       ,  407.5       ,  126.5167923 ],
        [ 450.5       ,  675.5       ,   37.34300613],
        [ 168.5       ,  649.5       ,   30.70016098],
        [ 347.5       ,  655.5       ,   34.82097244],
        [ 456.5       ,  646.5       ,   51.50242615],
        [  42.5       ,  664.5       ,   41.5030098 ],
        [ 445.5       ,  436.5       ,  115.59627533]]], dtype=float32)

In [193]:
circles = np.uint16(np.around(circles))

In [194]:
circles

array([[[450, 416, 133],
        [152, 420, 152],
        [252, 662,  27],
        [130, 412,  66],
        [ 58, 650,  55],
        [160, 672,  18],
        [302, 144, 146],
        [438, 656,  51],
        [ 56, 626,  51],
        [438, 634,  51],
        [468, 408, 127],
        [450, 676,  37],
        [168, 650,  31],
        [348, 656,  35],
        [456, 646,  52],
        [ 42, 664,  42],
        [446, 436, 116]]], dtype=uint16)

In [195]:
help(cv2.circle)

Help on built-in function circle:

circle(...)
    circle(img, center, radius, color[, thickness[, lineType[, shift]]]) -> img



In [196]:
for i in circles[0,:]:
    #draw outer circle
    cv2.circle(logo,(i[0],i[1]),i[2],(0,0,255),2)
    #draw inner circle
    cv2.circle(logo,(i[0],i[1]),2,(0,255,0),3)
    #save
    cv2.imwrite("/home/ashritha/ImageProcessing/HoughTransform/logo.png",logo)

In [197]:
plt.imshow(logo)
plt.show()